# Generated by Django 5.1.5 on 2025-01-23 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Order date and time')),
                ('customer_name', models.CharField(max_length=40, verbose_name='Customer name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Item name')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='Item description')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price per unit')),
                ('veg', models.BooleanField(verbose_name='Is vegetarian dish?')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='Item quantity')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeorder.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeorder.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(through='placeorder.CartItem', to='placeorder.product'),
        ),
    ]
