# Generated by Django 5.1.5 on 2025-01-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placeorder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart',
            new_name='order',
        ),
    ]
